# Generated by Django 4.2 on 2024-05-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="sizes",
        ),
        migrations.AddField(
            model_name="product",
            name="sizes",
            field=models.CharField(
                choices=[
                    ("s", "Size S"),
                    ("m", "Size M"),
                    ("l", "Size L"),
                    ("xl", "Size XL"),
                ],
                default="s",
            ),
        ),
    ]
