# Generated by Django 4.2 on 2024-05-05 13:17

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_productcolor_productsize_delete_size_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=shop.models.category_image_upload_path
            ),
        ),
    ]
