# Generated by Django 4.2 on 2024-05-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="primary",
            field=models.BooleanField(default=False),
        ),
    ]
