# Generated by Django 4.2 on 2024-05-05 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0005_productimage_primary"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productimage",
            unique_together={("product", "primary")},
        ),
    ]
