# Generated by Django 4.2 on 2024-05-05 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_alter_productimage_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productimage",
            unique_together=set(),
        ),
    ]
