# Generated by Django 4.2 on 2024-05-05 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_product_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="primary_image",
        ),
    ]
