# Generated by Django 4.2 on 2024-05-05 18:42

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_rename_image_product_primary_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="primary_image",
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="d",
                help_text="This the primary image for the product",
                upload_to=shop.models.product_primary_image_upload_path,
            ),
            preserve_default=False,
        ),
    ]
