# Generated by Django 4.2 on 2024-05-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_product_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                default="this is the product description",
                help_text="Description for the product",
            ),
            preserve_default=False,
        ),
    ]
