# Generated by Django 4.2 on 2024-05-11 19:23

import cart.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cart", "0002_alter_cart_data_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="data",
            field=models.JSONField(default=cart.models.default_cart_data),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
