# Generated by Django 4.2 on 2024-05-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0004_alter_cart_data_alter_cart_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="type",
            field=models.CharField(
                choices=[("cart", "cart"), ("wishlist", "wishlist")],
                default="cart",
                editable=False,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
