# Generated by Django 4.2 on 2024-05-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_alter_cart_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="data",
            field=models.JSONField(editable=False),
        ),
    ]
